### ISSUE TITLE
Move AI response generation from client to the backend

### ISSUE THREAD

**Issue by sorokinvj** [sorokinvj/transcription-server#11]
1. Implement a mechanism on the server to detect silences in the received audio data.
2. Use the silence detection to determine when to reset the block transcript.
3. Accumulate interim transcriptions into block transcripts on the server.
4. When a block transcript is complete (i.e., after detecting silence), send it to OpenAI for generating a response.

### Silence Detection

- Use an audio processing library or tool on the server to analyze the received audio data and detect silences.
- Define a threshold (e.g., 6 seconds) to determine when to consider the audio as silent.

### Transcription Accumulation

- Create a state on the server to manage block transcripts for each connected client.
- As interim transcriptions are received from the client, append them to the block transcript for that client.
- When silence is detected, consider the block transcript as complete.

### OpenAI Integration

- When a block transcript is complete, send it to OpenAI for generating a response using the logic extracted from the /api/generate endpoint.
- Store or process the AI-generated response as required.

### Client Communication

Update the WebSocket communication on the server to send back AI-generated responses as "questions" messages

**Comment by sorokinvj** [comment]
Managing state in a Node.js application is different from managing state in a frontend framework like React. In Node.js, state management often revolves around handling data persistence, session management, and caching. Here's a high-level overview of the different approaches to manage state in Node.js:

### In-Memory State:

**Description**: Store state directly in the application's memory.
**Pros**: Fast access times; no need for external systems.
**Cons**: Not persistent (data is lost when the server restarts); not scalable for large applications; potential memory leak issues.

### Databases:

**Description**: Use relational (e.g., PostgreSQL, MySQL) or NoSQL (e.g., MongoDB, Cassandra) databases to persist state.
**Pros**: Persistent storage; scalable; ACID properties (for relational databases).
**Cons**: Slower access times compared to in-memory; overhead of database operations.

### Caching Systems:

**Description**: Use caching systems like Redis or Memcached to store frequently accessed data.
**Pros**: Fast access times; reduces database load; scalable.
**Cons**: Not suitable for long-term persistence; additional infrastructure setup.

### Session Management:

**Description**: Store user session data either in-memory, in a database, or using external stores like Redis.
**Pros**: Enables user-specific state management; can be combined with JWTs for authentication.
**Cons**: Managing session expiration; potential overhead.

### File System:

**Description**: Store state as files on the server's file system.
**Pros**: Persistent storage; suitable for configuration data or logs.
**Cons**: Slower access times; not scalable for frequent read/write operations.

### Message Brokers:

**Description**: Use message brokers like RabbitMQ or Kafka to manage state across distributed systems. 
**Pros**: Enables event-driven architectures; scalable; decouples producers and consumers.
**Cons**: Additional infrastructure setup; complexity in ensuring message delivery.

### State Management Libraries:

**Description**: Use libraries or frameworks designed for state management in Node.js (e.g., node-cache, session middleware for Express).
**Pros**: Abstractions over common state management operations; integrates with popular Node.js frameworks.
**Cons**: Dependency on third-party libraries; potential overhead.

### Distributed State:

**Description**: Use distributed systems principles to manage state across multiple nodes or services (e.g., using etcd or **Consul** for service discovery and configuration).
**Pros**: Scalable; fault-tolerant; suitable for microservices architectures.
**Cons**: Complexity in setup and management; network overhead.

When choosing an approach, it's essential to consider the application's requirements, the expected load, the type of data being managed, and the desired level of persistence and scalability.

For your specific use case of accumulating transcriptions and managing AI-generated responses, a combination of in-memory state (for short-lived data) and caching systems (for faster access to frequently used data) might be suitable.

**Comment by sorokinvj** [comment]
## Event-Driven Architecture (EDA)

### What is EDA?
EDA is a software architecture paradigm where components execute in response to events. An event is a change in state, and components can produce or consume events.

### Key Concepts:
- **Event Producers**: Generate events and send them to a broker or bus.
- **Event Consumers**: Listen for specific events and take action when they occur.
- **Event Broker/Bus**: Middleware that manages the transmission of events from producers to consumers.

### Benefits:
- **Scalability**: Easily scale specific parts of a system.
- **Decoupling**: Producers and consumers are decoupled, promoting modular design.
- **Flexibility**: Easily add new event-driven functionalities.

### Challenges:
- **Complexity**: Can be harder to design and debug due to asynchronous nature.
- **Ordering**: Ensuring the correct order of events can be challenging.

---

## RabbitMQ

### What is RabbitMQ?
RabbitMQ is an open-source message broker that supports multiple messaging protocols. It's widely used for implementing EDA.

### Key Concepts:
- **Producer**: Sends messages.
- **Consumer**: Receives messages.
- **Exchange**: Routes messages based on rules and bindings.
- **Queue**: Stores messages waiting to be processed by consumers.
- **Binding**: Links an exchange to a queue.

### Basic Workflow:
1. A **producer** sends a message to an **exchange** in RabbitMQ.
2. The **exchange** routes the message to one or more **queues** based on bindings.
3. **Consumers** listen to queues and process messages from them.

### Benefits:
- **Reliability**: Supports message durability and acknowledgments.
- **Scalability**: Can handle high throughput and has clustering capabilities.
- **Flexibility**: Supports various messaging patterns like pub-sub, direct messaging, and RPC.

### Challenges:
- **Operational Complexity**: Requires monitoring, tuning, and maintenance.

### Quick Start with RabbitMQ:
1. **Installation**: Use Docker for a quick setup: `docker run -d --name rabbitmq -p 15672:15672 -p 5672:5672 rabbitmq:management`
2. **Access Management UI**: Visit `http://localhost:15672/` (default login: `guest/guest`).
3. **Integration with Node.js**: Use the `amqplib` library.
   - **Send a message**: Create a connection, channel, declare a queue, and send a message.
   - **Receive a message**: Create a connection, channel, declare the same queue, and consume messages.
   
###  Example (Node.js):
```
// Producer
const amqp = require('amqplib/callback_api');
amqp.connect('amqp://localhost', (error, connection) => {
  const channel = connection.createChannel();
  channel.assertQueue('myQueue');
  channel.sendToQueue('myQueue', Buffer.from('Hello World!'));
});

// Consumer
amqp.connect('amqp://localhost', (error, connection) => {
  const channel = connection.createChannel();
  channel.assertQueue('myQueue');
  channel.consume('myQueue', (msg) => {
    console.log(`Received: ${msg.content.toString()}`);
  });
});
```

**Comment by valieff** [comment]
Expecting to get a valid JSON string on frontend. Let's shorten the keys to "q" instead of "res" and "h" instead of "hint". Rationale: OpenAI API speed depends on output length, so I think it's a good idea to condense output to shortest possible format. 

### Examples of valid output:

"h" key is optional and only exists if one or more meaningful questions are extracted.

**1. OpenAI detects that there is no question:**

`{"q": ""}`

**2. OpenAI detects multiple questions which are personal — a hint would not be really helpful. "P" stands for "personal question":**

`{"q": ["Your age", "When you finished studies?"], "h": ["p"]}`

**3. OpenAI detects one question which is not a personal question. Hint is in the format of an array of bullet points.**

`{"q": ["When to use Redux in React?"], "h": ["Should be used in following scenarios:", "State management becomes complex", "Data needs to be shared across components", "Predictable and centralized state changes are required", "Scalability and maintainability are essential", "Middleware integration (e.g., async actions) is needed."]}`

**4. Another example of valid output:**

`{"res": ["Cookies vs local storage"], "hint": ["Cookies: ", "Small text files (around 4KB)", "Sent with every HTTP request","Used for session management and server-side tasks", "Local Storage:", "Larger storage capacity (up to 5-10MB)", "Faster as data isn&apos;t sent with each request", "Ideal for client-side data like caching or user preferences"]}`

**Occasionally OpenAI does not respect word limit set in prompt and outputs a very long hint. This breaks the valid JSON string format. Example of problematic output:**

`{"res": ["Cookies vs local storage"], "hint": ["Cookies: ", "Small text files (around 4KB)", "Very long hint that exceeds token limit`

Notice missing `"]}` at the end of the string. Possible solutions: use regex to fix invalid JSON strings before sending to frontend or validate output on frontend.

**Comment by sorokinvj** [comment]
@valieff  
Could we set `q: []` and `"h": []` where there is no question and hint? We should always aim for the same type

**Comment by sorokinvj** [comment]
done in #13
